"""
配置包初始化文件
"""

from .settings import (
    BASE_DIR,
    INPUT_DIR,
    OUTPUT_DIR,
    STATS_REPORT_FILE,
    ANALYSIS_SUMMARY_FILE,
    PROCESSED_FILES_RECORD,
    ALLOWED_EXTENSIONS,
    IGNORE_PATTERN,
    THRESHOLDS,
    ALERT_CONFIG,
    NGINX_LOG_PATTERN,
    TIME_FORMAT,
    STATS_CONFIG,
)

__all__ = [
    'BASE_DIR',
    'INPUT_DIR',
    'OUTPUT_DIR',
    'STATS_REPORT_FILE',
    'ANALYSIS_SUMMARY_FILE',
    'PROCESSED_FILES_RECORD',
    'ALLOWED_EXTENSIONS',
    'IGNORE_PATTERN',
    'THRESHOLDS',
    'ALERT_CONFIG',
    'NGINX_LOG_PATTERN',
    'TIME_FORMAT',
    'STATS_CONFIG',
]
